name: Rentré_d_argent_personnes
description: Prédire si une personne est riche ou pauvre (+ ou - de 50k$)
Dataset: https://www.kaggle.com/datasets/uciml/adult-census-income

channels: 
  - defaults
  - conda-forge

dependencies:
  - python=3.12.7
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - ipykernel
  - seaborn
  - pip:
    - catboost